export const portfolioData = {
  name: "Sahil Atram",
  title: "MERN Stack & AI Developer",
  email: "sahilatram303@gmail.com",
  phone: "+91 9356866994",
  location: "Nagpur, Maharashtra",
  education: "B.Tech CSE-IoT — Yeshwantrao Chavan College of Engineering, Nagpur",
  internship: "MERN Stack Web Developer Intern at Monikwave Creatives (4 months)",
  currentFocus: "AI-powered web apps & intelligent systems",
  skills: {
    frontend: ["React", "Next.js", "Tailwind CSS", "TypeScript", "React-Redux"],
    backend: ["Node.js", "Express.js", "REST APIs", "Socket.io"],
    database: ["MongoDB", "Mongoose"],
    ai: ["LLM APIs", "API Integration", "AI Prompts"],
    languages: ["JavaScript", "Python"],
    tools: ["Git/GitHub", "Postman", "Vercel", "VS Code", "WebRTC"],
  },
  projects: [
    {
      title: "SyncMeet",
      description: "Video conferencing app with real-time communication, screen sharing, and chat using WebRTC and MERN stack.",
      tags: ["React-Redux", "WebRTC", "Socket.io", "MERN"],
      category: "WebRTC",
      live: "https://sync-meet-video-confrencing-applica.vercel.app/",
      github: "https://github.com/Sahil071803/SyncMeet---Video-Confrencing-Application.git",
    },
    {
      title: "Studius",
      description: "AI-powered notes summarizer using LLM APIs to generate concise summaries from long documents.",
      tags: ["React", "LLM API", "MERN Stack"],
      category: "AI",
      live: "https://studius-ai-notes-summerizer-oj9o.vercel.app",
      github: "https://github.com/Sahil071803/studius-ai-notes-summerizer.git",
    },
    {
      title: "Nexa Ai",
      description: "Intelligent chatbot application powered by LLM APIs with real-time conversational responses.",
      tags: ["React", "LLM API", "MERN Stack"],
      category: "AI",
      live: "https://ai-chat-bot-application-smoky.vercel.app/",
      github: "https://github.com/Sahil071803/Ai-Chat-Bot-Application.git",
    },
    {
      title: "Weather Climate App",
      description: "A weather and climate application providing real-time forecasts, temperature updates, and climate data visualization.",
      tags: ["React", "API", "Weather"],
      category: "MERN",
      live: "https://weather-climate-app.vercel.app",
      github: "https://github.com/Sahil071803/Weather-Climate-app.git",
    },
    {
      title: "Portfolio Website",
      description: "Futuristic AI-powered portfolio built with Next.js, TypeScript, and Tailwind CSS featuring dark/light theme, animations, and AI features.",
      tags: ["Next.js", "TypeScript", "Tailwind CSS", "Framer Motion"],
      category: "AI",
      live: "https://portfolio-website-nu-opal-68.vercel.app",
      github: "https://github.com/Sahil071803/Portfolio-Website.git",
    },
  ],
};
